!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  host: cwcc.compuware.com
  port: 16196
  runtimeConfig: ispw
  stream: GITDEMO1
  application: GITE
  pathMappings:
  - path: "**/Sources/**"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: cbldb2
      ispwType: COB
      sql: 'Yes'
    - fileExtension: pli
      ispwType: PLI
    - fileExtension: cpy
      ispwType: COPY
    - fileExtension: incl
      ispwType: INCL
    - fileExtension: jcl
      ispwType: JOB